// services/calling/OutboundICECandidateBuffer.js
/**
 * OutboundICECandidateBuffer
 *
 * Buffers ICE candidates generated by the server that are destined for the client.
 * Holds candidates until the client signals it's ready to receive them (after
 * setRemoteDescription is called on the client side).
 */

export class OutboundICECandidateBuffer {
    constructor() {
        this.candidateBuffer = new Map(); // callId -> candidate[]
        this.readyFlags = new Map(); // callId -> boolean
    }

    buffer(callId, candidate) {
        if (!this.candidateBuffer.has(callId)) {
            this.candidateBuffer.set(callId, []);
        }
        this.candidateBuffer.get(callId).push(candidate);
    }

    flush(callId) {
        const candidates = this.candidateBuffer.get(callId) || [];
        this.candidateBuffer.delete(callId);
        return candidates;
    }

    isReady(callId) {
        return this.readyFlags.get(callId) === true;
    }

    markReady(callId) {
        const wasNotReady = !this.readyFlags.get(callId);
        this.readyFlags.set(callId, true);
        return wasNotReady;
    }

    cleanup(callId) {
        this.candidateBuffer.delete(callId);
        this.readyFlags.delete(callId);
    }
}
