[rtpengine]
interface = external/172.31.10.3!127.0.0.1;internal/172.31.20.3
listen-ng = 0.0.0.0:22222
port-min = 30000
port-max = 30099
delete-delay = 0
log-level = 6
log-stderr = true
foreground = true
